<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string></string>
	</array>
	<key>foldingStartMarker</key>
	<string>^(##)\s+</string>
	<key>foldingStopMarker</key>
	<string>(?=^(##)\s+)</string>
	<key>name</key>
	<string>CodeCell</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>support.constant.tag.python.codecell</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(##)(?=\s+|\Z).*</string>
			<key>name</key>
			<string>support.constant.python.codecell</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.python</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.python.codecell</string>
	<key>uuid</key>
	<string>c71c37f6-2b16-4ed8-90f5-130715f3d565</string>
</dict>
</plist>
