<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string></string>
	</array>
	<key>name</key>
	<string>CodeCell</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>^((##)((\s+)(.*)$|\n))</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.constant.python.codecell</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.cell.begin.python.codecell</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.cell.header.python.codecell</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>meta.cell-content.python.codecell</string>
			<key>end</key>
			<string>(?=(^##)(\s+.*$|\n))</string>
			<key>endCaptures</key>
			<dict>
			</dict>
			<key>name</key>
			<string>meta.cell.python.codecell</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.python</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>source.python</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.python.codecell</string>
	<key>uuid</key>
	<string>c71c37f6-2b16-4ed8-90f5-130715f3d565</string>
</dict>
</plist>
