<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ipy</string>
	</array>
	<key>name</key>
	<string>IPython</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>^((##)((\s+)(.*)$|\n))</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.type.section.cell.heading.ipython</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.cell.begin.ipython</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>entity.name.section.cell.heading.ipython</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>code/markup cell</string>
			<key>contentName</key>
			<string>meta.section.cell.content.ipython</string>
			<key>end</key>
			<string>(?=(^##)(\s+.*$|\n))</string>
			<key>endCaptures</key>
			<dict>
			</dict>
			<key>name</key>
			<string>meta.section.cell.ipython</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#ipython_magic</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#ipython_shell_command</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.python</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#ipython_magic</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#ipython_shell_command</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.python</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>ipython_magic</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.function.magic.ipython</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>ipython magic function</string>
			<key>match</key>
			<string>((\%+)(\w+))(\s+(.*)\n|\b)</string>
			<key>name</key>
			<string>meta.function.magic.ipython</string>
		</dict>
		<key>ipython_shell_command</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.character.shell-command.ipython</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>shell escape</string>
			<key>match</key>
			<string>^((!)(.+))</string>
			<key>name</key>
			<string>meta.function.shell-command.ipython</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.python.ipython</string>
	<key>uuid</key>
	<string>c71c37f6-2b16-4ed8-90f5-130715f3d565</string>
</dict>
</plist>
